// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.category */
export type CategoryCategoryId = number & { __brand: 'CategoryCategoryId' };

/** Represents the table public.category */
export default interface Category {
  category_id: CategoryCategoryId;

  name: string;

  last_update: Date;
}

/** Represents the initializer for the table public.category */
export interface CategoryInitializer {
  /** Default value: nextval('category_category_id_seq'::regclass) */
  category_id?: CategoryCategoryId;

  name: string;

  /** Default value: now() */
  last_update?: Date;
}

/** Represents the mutator for the table public.category */
export interface CategoryMutator {
  category_id?: CategoryCategoryId;

  name?: string;

  last_update?: Date;
}
