// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type CountryCountryId } from './Country';

/** Identifier type for public.city */
export type CityCityId = number & { __brand: 'CityCityId' };

/** Represents the table public.city */
export default interface City {
  city_id: CityCityId;

  city: string;

  country_id: CountryCountryId;

  last_update: Date;
}

/** Represents the initializer for the table public.city */
export interface CityInitializer {
  /** Default value: nextval('city_city_id_seq'::regclass) */
  city_id?: CityCityId;

  city: string;

  country_id: CountryCountryId;

  /** Default value: now() */
  last_update?: Date;
}

/** Represents the mutator for the table public.city */
export interface CityMutator {
  city_id?: CityCityId;

  city?: string;

  country_id?: CountryCountryId;

  last_update?: Date;
}
