// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.country */
export type CountryCountryId = number & { __brand: 'CountryCountryId' };

/** Represents the table public.country */
export default interface Country {
  country_id: CountryCountryId;

  country: string;

  last_update: Date;
}

/** Represents the initializer for the table public.country */
export interface CountryInitializer {
  /** Default value: nextval('country_country_id_seq'::regclass) */
  country_id?: CountryCountryId;

  country: string;

  /** Default value: now() */
  last_update?: Date;
}

/** Represents the mutator for the table public.country */
export interface CountryMutator {
  country_id?: CountryCountryId;

  country?: string;

  last_update?: Date;
}
