// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type AddressAddressId } from './Address';

/** Identifier type for public.customer */
export type CustomerCustomerId = number & { __brand: 'CustomerCustomerId' };

/** Represents the table public.customer */
export default interface Customer {
  customer_id: CustomerCustomerId;

  store_id: number;

  first_name: string;

  last_name: string;

  email: string | null;

  address_id: AddressAddressId;

  activebool: boolean;

  create_date: Date;

  last_update: Date | null;

  active: number | null;
}

/** Represents the initializer for the table public.customer */
export interface CustomerInitializer {
  /** Default value: nextval('customer_customer_id_seq'::regclass) */
  customer_id?: CustomerCustomerId;

  store_id: number;

  first_name: string;

  last_name: string;

  email?: string | null;

  address_id: AddressAddressId;

  /** Default value: true */
  activebool?: boolean;

  /** Default value: ('now'::text)::date */
  create_date?: Date;

  /** Default value: now() */
  last_update?: Date | null;

  active?: number | null;
}

/** Represents the mutator for the table public.customer */
export interface CustomerMutator {
  customer_id?: CustomerCustomerId;

  store_id?: number;

  first_name?: string;

  last_name?: string;

  email?: string | null;

  address_id?: AddressAddressId;

  activebool?: boolean;

  create_date?: Date;

  last_update?: Date | null;

  active?: number | null;
}
