// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ActorActorId } from './Actor';
import { type FilmFilmId } from './Film';

/** Represents the table public.film_actor */
export default interface FilmActor {
  actor_id: ActorActorId;

  film_id: FilmFilmId;

  last_update: Date;
}

/** Represents the initializer for the table public.film_actor */
export interface FilmActorInitializer {
  actor_id: ActorActorId;

  film_id: FilmFilmId;

  /** Default value: now() */
  last_update?: Date;
}

/** Represents the mutator for the table public.film_actor */
export interface FilmActorMutator {
  actor_id?: ActorActorId;

  film_id?: FilmFilmId;

  last_update?: Date;
}
