// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type FilmFilmId } from './Film';
import { type CategoryCategoryId } from './Category';

/** Represents the table public.film_category */
export default interface FilmCategory {
  film_id: FilmFilmId;

  category_id: CategoryCategoryId;

  last_update: Date;
}

/** Represents the initializer for the table public.film_category */
export interface FilmCategoryInitializer {
  film_id: FilmFilmId;

  category_id: CategoryCategoryId;

  /** Default value: now() */
  last_update?: Date;
}

/** Represents the mutator for the table public.film_category */
export interface FilmCategoryMutator {
  film_id?: FilmFilmId;

  category_id?: CategoryCategoryId;

  last_update?: Date;
}
