// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type CustomerCustomerId } from './Customer';
import { type StaffStaffId } from './Staff';
import { type RentalRentalId } from './Rental';

/** Identifier type for public.payment */
export type PaymentPaymentId = number & { __brand: 'PaymentPaymentId' };

/** Represents the table public.payment */
export default interface Payment {
  payment_id: PaymentPaymentId;

  customer_id: CustomerCustomerId;

  staff_id: StaffStaffId;

  rental_id: RentalRentalId;

  amount: string;

  payment_date: Date;
}

/** Represents the initializer for the table public.payment */
export interface PaymentInitializer {
  /** Default value: nextval('payment_payment_id_seq'::regclass) */
  payment_id?: PaymentPaymentId;

  customer_id: CustomerCustomerId;

  staff_id: StaffStaffId;

  rental_id: RentalRentalId;

  amount: string;

  payment_date: Date;
}

/** Represents the mutator for the table public.payment */
export interface PaymentMutator {
  payment_id?: PaymentPaymentId;

  customer_id?: CustomerCustomerId;

  staff_id?: StaffStaffId;

  rental_id?: RentalRentalId;

  amount?: string;

  payment_date?: Date;
}
