// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type InventoryInventoryId } from './Inventory';
import { type CustomerCustomerId } from './Customer';
import { type StaffStaffId } from './Staff';

/** Identifier type for public.rental */
export type RentalRentalId = number & { __brand: 'RentalRentalId' };

/** Represents the table public.rental */
export default interface Rental {
  rental_id: RentalRentalId;

  rental_date: Date;

  inventory_id: InventoryInventoryId;

  customer_id: CustomerCustomerId;

  return_date: Date | null;

  staff_id: StaffStaffId;

  last_update: Date;
}

/** Represents the initializer for the table public.rental */
export interface RentalInitializer {
  /** Default value: nextval('rental_rental_id_seq'::regclass) */
  rental_id?: RentalRentalId;

  rental_date: Date;

  inventory_id: InventoryInventoryId;

  customer_id: CustomerCustomerId;

  return_date?: Date | null;

  staff_id: StaffStaffId;

  /** Default value: now() */
  last_update?: Date;
}

/** Represents the mutator for the table public.rental */
export interface RentalMutator {
  rental_id?: RentalRentalId;

  rental_date?: Date;

  inventory_id?: InventoryInventoryId;

  customer_id?: CustomerCustomerId;

  return_date?: Date | null;

  staff_id?: StaffStaffId;

  last_update?: Date;
}
