// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type AddressAddressId } from './Address';

/** Identifier type for public.staff */
export type StaffStaffId = number & { __brand: 'StaffStaffId' };

/** Represents the table public.staff */
export default interface Staff {
  staff_id: StaffStaffId;

  first_name: string;

  last_name: string;

  address_id: AddressAddressId;

  email: string | null;

  store_id: number;

  active: boolean;

  username: string;

  password: string | null;

  last_update: Date;

  picture: unknown | null;
}

/** Represents the initializer for the table public.staff */
export interface StaffInitializer {
  /** Default value: nextval('staff_staff_id_seq'::regclass) */
  staff_id?: StaffStaffId;

  first_name: string;

  last_name: string;

  address_id: AddressAddressId;

  email?: string | null;

  store_id: number;

  /** Default value: true */
  active?: boolean;

  username: string;

  password?: string | null;

  /** Default value: now() */
  last_update?: Date;

  picture?: unknown | null;
}

/** Represents the mutator for the table public.staff */
export interface StaffMutator {
  staff_id?: StaffStaffId;

  first_name?: string;

  last_name?: string;

  address_id?: AddressAddressId;

  email?: string | null;

  store_id?: number;

  active?: boolean;

  username?: string;

  password?: string | null;

  last_update?: Date;

  picture?: unknown | null;
}
