// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type StaffStaffId } from './Staff';
import { type AddressAddressId } from './Address';

/** Identifier type for public.store */
export type StoreStoreId = number & { __brand: 'StoreStoreId' };

/** Represents the table public.store */
export default interface Store {
  store_id: StoreStoreId;

  manager_staff_id: StaffStaffId;

  address_id: AddressAddressId;

  last_update: Date;
}

/** Represents the initializer for the table public.store */
export interface StoreInitializer {
  /** Default value: nextval('store_store_id_seq'::regclass) */
  store_id?: StoreStoreId;

  manager_staff_id: StaffStaffId;

  address_id: AddressAddressId;

  /** Default value: now() */
  last_update?: Date;
}

/** Represents the mutator for the table public.store */
export interface StoreMutator {
  store_id?: StoreStoreId;

  manager_staff_id?: StaffStaffId;

  address_id?: AddressAddressId;

  last_update?: Date;
}
