// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.user */
export type UserId = number & { __brand: 'UserId' };

/** Represents the table public.user */
export default interface User {
  id: UserId;

  firstName: string | null;

  lastName: string | null;

  age: number | null;
}

/** Represents the initializer for the table public.user */
export interface UserInitializer {
  /** Default value: nextval('user_id_seq'::regclass) */
  id?: UserId;

  firstName?: string | null;

  lastName?: string | null;

  age?: number | null;
}

/** Represents the mutator for the table public.user */
export interface UserMutator {
  id?: UserId;

  firstName?: string | null;

  lastName?: string | null;

  age?: number | null;
}
