// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.ContentType */
enum ContentType {
  Video = 'Video',
  Blog = 'Blog',
  Gist = 'Gist',
  Podcast = 'Podcast',
};

export default ContentType;
