// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type default as ContentType } from './ContentType';
import { type UserId } from './User';

/** Identifier type for public.Content */
export type ContentId = string & { __brand: 'ContentId' };

/** Represents the table public.Content */
export default interface Content {
  id: ContentId;

  createdAt: Date;

  updatedAt: Date;

  title: string;

  type: ContentType;

  content_url: string;

  userId: UserId | null;
}

/** Represents the initializer for the table public.Content */
export interface ContentInitializer {
  id: ContentId;

  /** Default value: CURRENT_TIMESTAMP */
  createdAt?: Date;

  updatedAt: Date;

  title: string;

  type: ContentType;

  content_url: string;

  userId?: UserId | null;
}

/** Represents the mutator for the table public.Content */
export interface ContentMutator {
  id?: ContentId;

  createdAt?: Date;

  updatedAt?: Date;

  title?: string;

  type?: ContentType;

  content_url?: string;

  userId?: UserId | null;
}
