// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type default as Qualification } from './Qualification';
import { type UserId } from './User';

/** Identifier type for public.Education */
export type EducationId = string & { __brand: 'EducationId' };

/** Represents the table public.Education */
export default interface Education {
  id: EducationId;

  createdAt: Date;

  updatedAt: Date;

  school: string;

  qualification: Qualification;

  field: string;

  from: Date;

  to: Date;

  userId: UserId;
}

/** Represents the initializer for the table public.Education */
export interface EducationInitializer {
  id: EducationId;

  /** Default value: CURRENT_TIMESTAMP */
  createdAt?: Date;

  updatedAt: Date;

  school: string;

  qualification: Qualification;

  field: string;

  from: Date;

  to: Date;

  userId: UserId;
}

/** Represents the mutator for the table public.Education */
export interface EducationMutator {
  id?: EducationId;

  createdAt?: Date;

  updatedAt?: Date;

  school?: string;

  qualification?: Qualification;

  field?: string;

  from?: Date;

  to?: Date;

  userId?: UserId;
}
