// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type UserId } from './User';

/** Identifier type for public.Experience */
export type ExperienceId = string & { __brand: 'ExperienceId' };

/** Represents the table public.Experience */
export default interface Experience {
  id: ExperienceId;

  createdAt: Date;

  updatedAt: Date;

  position: string;

  company: string;

  from: Date;

  to: Date;

  description: string | null;

  userId: UserId;
}

/** Represents the initializer for the table public.Experience */
export interface ExperienceInitializer {
  id: ExperienceId;

  /** Default value: CURRENT_TIMESTAMP */
  createdAt?: Date;

  updatedAt: Date;

  position: string;

  company: string;

  from: Date;

  to: Date;

  description?: string | null;

  userId: UserId;
}

/** Represents the mutator for the table public.Experience */
export interface ExperienceMutator {
  id?: ExperienceId;

  createdAt?: Date;

  updatedAt?: Date;

  position?: string;

  company?: string;

  from?: Date;

  to?: Date;

  description?: string | null;

  userId?: UserId;
}
