// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type UserId } from './User';

/** Identifier type for public.Hackathon */
export type HackathonId = string & { __brand: 'HackathonId' };

/** Represents the table public.Hackathon */
export default interface Hackathon {
  id: HackathonId;

  createdAt: Date;

  updatedAt: Date;

  name: string;

  description: string;

  technologies: string[] | null;

  from: Date;

  to: Date;

  link: string;

  userId: UserId;
}

/** Represents the initializer for the table public.Hackathon */
export interface HackathonInitializer {
  id: HackathonId;

  /** Default value: CURRENT_TIMESTAMP */
  createdAt?: Date;

  updatedAt: Date;

  name: string;

  description: string;

  technologies?: string[] | null;

  from: Date;

  to: Date;

  link: string;

  userId: UserId;
}

/** Represents the mutator for the table public.Hackathon */
export interface HackathonMutator {
  id?: HackathonId;

  createdAt?: Date;

  updatedAt?: Date;

  name?: string;

  description?: string;

  technologies?: string[] | null;

  from?: Date;

  to?: Date;

  link?: string;

  userId?: UserId;
}
