// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type UserId } from './User';

/** Identifier type for public.JobApplication */
export type JobApplicationId = string & { __brand: 'JobApplicationId' };

/** Represents the table public.JobApplication */
export default interface JobApplication {
  id: JobApplicationId;

  createdAt: Date;

  updatedAt: Date;

  job_title: string;

  description: string;

  job_posting_url: string;

  cover_letter: string;

  resume: string;

  userId: UserId;

  resumeId: string | null;
}

/** Represents the initializer for the table public.JobApplication */
export interface JobApplicationInitializer {
  id: JobApplicationId;

  /** Default value: CURRENT_TIMESTAMP */
  createdAt?: Date;

  updatedAt: Date;

  job_title: string;

  description: string;

  job_posting_url: string;

  cover_letter: string;

  resume: string;

  userId: UserId;

  resumeId?: string | null;
}

/** Represents the mutator for the table public.JobApplication */
export interface JobApplicationMutator {
  id?: JobApplicationId;

  createdAt?: Date;

  updatedAt?: Date;

  job_title?: string;

  description?: string;

  job_posting_url?: string;

  cover_letter?: string;

  resume?: string;

  userId?: UserId;

  resumeId?: string | null;
}
