// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type UserId } from './User';

/** Identifier type for public.Key */
export type KeyId = string & { __brand: 'KeyId' };

/** Represents the table public.Key */
export default interface Key {
  _id: KeyId;

  hashed_password: string | null;

  user_id: UserId;
}

/** Represents the initializer for the table public.Key */
export interface KeyInitializer {
  _id: KeyId;

  hashed_password?: string | null;

  user_id: UserId;
}

/** Represents the mutator for the table public.Key */
export interface KeyMutator {
  _id?: KeyId;

  hashed_password?: string | null;

  user_id?: UserId;
}
