// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public._prisma_migrations */
export type PrismaMigrationsId = string & { __brand: 'PrismaMigrationsId' };

/** Represents the table public._prisma_migrations */
export default interface PrismaMigrations {
  id: PrismaMigrationsId;

  checksum: string;

  finished_at: Date | null;

  migration_name: string;

  logs: string | null;

  rolled_back_at: Date | null;

  started_at: Date;

  applied_steps_count: number;
}

/** Represents the initializer for the table public._prisma_migrations */
export interface PrismaMigrationsInitializer {
  id: PrismaMigrationsId;

  checksum: string;

  finished_at?: Date | null;

  migration_name: string;

  logs?: string | null;

  rolled_back_at?: Date | null;

  /** Default value: now() */
  started_at?: Date;

  /** Default value: 0 */
  applied_steps_count?: number;
}

/** Represents the mutator for the table public._prisma_migrations */
export interface PrismaMigrationsMutator {
  id?: PrismaMigrationsId;

  checksum?: string;

  finished_at?: Date | null;

  migration_name?: string;

  logs?: string | null;

  rolled_back_at?: Date | null;

  started_at?: Date;

  applied_steps_count?: number;
}
