// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type UserId } from './User';

/** Identifier type for public.Project */
export type ProjectId = string & { __brand: 'ProjectId' };

/** Represents the table public.Project */
export default interface Project {
  id: ProjectId;

  createdAt: Date;

  updatedAt: Date;

  name: string;

  description: string;

  repoUrl: string;

  image_url: string | null;

  languages: string[] | null;

  libraries: string[] | null;

  userId: UserId | null;
}

/** Represents the initializer for the table public.Project */
export interface ProjectInitializer {
  id: ProjectId;

  /** Default value: CURRENT_TIMESTAMP */
  createdAt?: Date;

  updatedAt: Date;

  name: string;

  description: string;

  repoUrl: string;

  image_url?: string | null;

  languages?: string[] | null;

  libraries?: string[] | null;

  userId?: UserId | null;
}

/** Represents the mutator for the table public.Project */
export interface ProjectMutator {
  id?: ProjectId;

  createdAt?: Date;

  updatedAt?: Date;

  name?: string;

  description?: string;

  repoUrl?: string;

  image_url?: string | null;

  languages?: string[] | null;

  libraries?: string[] | null;

  userId?: UserId | null;
}
