// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.Qualification */
enum Qualification {
  Certificate = 'Certificate',
  Bachelors = 'Bachelors',
  Masters = 'Masters',
  PhD = 'PhD',
};

export default Qualification;
