// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type UserId } from './User';

/** Identifier type for public.Resume */
export type ResumeId = string & { __brand: 'ResumeId' };

/** Represents the table public.Resume */
export default interface Resume {
  id: ResumeId;

  createdAt: Date;

  updatedAt: Date;

  body: string;

  jobAplicationId: string | null;

  userId: UserId;
}

/** Represents the initializer for the table public.Resume */
export interface ResumeInitializer {
  id: ResumeId;

  /** Default value: CURRENT_TIMESTAMP */
  createdAt?: Date;

  updatedAt: Date;

  body: string;

  jobAplicationId?: string | null;

  userId: UserId;
}

/** Represents the mutator for the table public.Resume */
export interface ResumeMutator {
  id?: ResumeId;

  createdAt?: Date;

  updatedAt?: Date;

  body?: string;

  jobAplicationId?: string | null;

  userId?: UserId;
}
