// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type UserId } from './User';

/** Identifier type for public.Session */
export type SessionId = string & { __brand: 'SessionId' };

/** Represents the table public.Session */
export default interface Session {
  _id: SessionId;

  user_id: UserId;

  active_expires: string;

  idle_expires: string;
}

/** Represents the initializer for the table public.Session */
export interface SessionInitializer {
  _id: SessionId;

  user_id: UserId;

  active_expires: string;

  idle_expires: string;
}

/** Represents the mutator for the table public.Session */
export interface SessionMutator {
  _id?: SessionId;

  user_id?: UserId;

  active_expires?: string;

  idle_expires?: string;
}
